framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'noreply-admin@lebonangle.com'
        headers:
            from: 'Administrateur <noreply-admin@lebonangle.com>'