vich_uploader:
  db_driver: orm

  mappings:
    picture:
      uri_prefix: /media/image/advert
      upload_destination: '%kernel.project_dir%/public/media/image/advert'
      # Will rename uploaded files using a uniqueid as a prefix.
      namer: Vich\UploaderBundle\Naming\OrignameNamer