vich_uploader:
  db_driver: orm

  mappings:
    advert_image:
      uri_prefix: /images/adverts
      upload_destination: '%kernel.project_dir%/public/images/adverts'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer